version: "3.8"
services:
    frontend_server:
        restart: "on-failure"
        build:
            context: "./front"
            dockerfile: Dockerfile
        container_name: "react-jeju-gamsukkwang-app"
        ports:
            - 80:80
        links:
            - backend_server

    backend_server:
        restart: "on-failure"
        build:
            context: "./back"
            dockerfile: Dockerfile
        container_name: "node-jeju-gamsukkwang-app"
        ports:
            - 5000:5000

    ai_server:
        restart: "on-failure"
        build:
            context: "./ai"
            dockerfile: Dockerfile
        container_name: "python-jeju-gamsukkwang-app"
        ports:
            - 5003:5003
        links:
            - backend_server
